version: '3'
services:
  api:
    container_name: api-container
    build: .
    image: clean-code-ts
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-code-ts/dist
    ports:
      - "5050:5050"
  node:
    image: node:16
